In [7]:
import pandas as pd
import numpy as np

In [59]:
!head ratings_long.csv

userId,movieId,rating
0,16,5
0,72,5
0,86,5
0,259,1
0,319,4
0,521,4
0,534,2
0,671,1
0,673,2

In [9]:
r = np.full((20, 1000),fill_value=np.nan)

In [10]:
df = pd.read_csv('ratings_long.csv')

In [11]:
for rec in df.itertuples():
    r[rec.userId][rec.movieId] = rec.rating

Note that $r$ matrix is $20 \times 1000$ with only <1\% full (highly sparse)

In [12]:
r

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan,  4., nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])

What if we define two matricies
- u = $20 \times 4$
- v = $4 \times 1000$


Then model $r$ as $u \times v$

Problem is we have to learn for $20 \times 4 + 4 \times 1000 = 4080$ parameters (better than 20.000 x 0.99 missing values)

## Problem

1. Define a convex loss function wrt $u$ and $v$
- Solve using gradient descent algorithm explained in **I Do**
- Use any regulatizer $L1$ or $L2$ to prevent overfitting

## Veri Özeti Çıkarma

In [1]:
%%duckdb

summarize ratings_long.csv

,column_name,column_type,min,max,approx_unique,avg,std,q25,q50,q75,count,null_percentage
0,userId,BIGINT,0,19,22,8.58,6.08182067423628,3,9,14,200,0.0
1,movieId,BIGINT,5,998,206,493.17,289.9099168698744,241,489,746,200,0.0
2,rating,BIGINT,1,5,5,3.06,1.3095704923263427,2,3,4,200,0.0

In [5]:
%%duckdb

select count(rating) from ratings_long.csv group by rating

   count(rating)
0             37
1             41
2             29
3             37
4             56

In [10]:
%%duckdb

select movieid, count(movieid),  from ratings_long.csv group by movieid order by movieid

     movieId  count(movieid)
0          5               1
1         10               1
2         14               1
3         16               2
4         17               1
..       ...             ...
174      948               1
175      955               1
176      966               1
177      994               1
178      998               1

[179 rows x 2 columns]

## Verinin eğitim ve test olarak ayrılması

In [100]:
from sklearn.model_selection import train_test_split

X_df = df[["userId", "movieId"]]
Y_df = df["rating"]


X_train, X_test, y_train, y_test = train_test_split(X_df, Y_df, test_size=0.2, stratify=df['rating'])

train_df = X_train.copy()
train_df['rating'] = y_train

test_df = X_test.copy()
test_df['rating'] = y_test

r_train = np.zeros((20,1000))

r_test = np.zeros((20, 1000))


for _, row in train_df.iterrows():
    i, j = int(row['userId']), int(row['movieId'])
    r_train[i, j] = row['rating']

for _, row in test_df.iterrows():
    i, j = int(row['userId']), int(row['movieId'])
    r_test[i, j] = row['rating']

## Loss fonksiyonu hesaplama

In [99]:
def loss_function(y: float, y_pred: float) -> float:
    return np.mean((y-y_pred) ** 2)

 ## Model eğitimi

In [ ]:
def Predicter(r_train: np.ndarray, n_epoch: int, lmbd: float, lr: float, early_stopping: bool=True):
    u = np.random.randn(20, 4)  * np.sqrt(2 / (20 + 4))
    v = np.random.randn(4, 1000) * np.sqrt(2 / (4 + 1000))
    

    for epoch in range(n_epoch):

        y_pred = u@v
        
        d_u = -2 * (r_train - u@v) @ v.T + 2 * lmbd * u
        d_v = -2 * u.T @ (r_train- u@v) + 2 * lmbd * v

        print(f"Epoch: {epoch}----Gradient norm: {np.linalg.norm(y_pred)}----- {loss_function(r_train, y_pred):.4f}")


        if np.linalg.norm(y_pred) < 0.01 and early_stopping:
            break

        u -= lr * d_u
        v -= lr * d_v

    return u, v

## Model Değerlendirmesi

In [115]:
pred = Predicter(r_test, 100, 0.01, 0.0005)


pred

Epoch: 0----Gradient norm: 3.7987057402243076----- 0.0232
Epoch: 1----Gradient norm: 3.7831743622991825----- 0.0232
Epoch: 2----Gradient norm: 3.7679474918299034----- 0.0231
Epoch: 3----Gradient norm: 3.7530206062190947----- 0.0231
Epoch: 4----Gradient norm: 3.7383893081815254----- 0.0231
Epoch: 5----Gradient norm: 3.724049322206102----- 0.0231
Epoch: 6----Gradient norm: 3.7099964911438494----- 0.0231
Epoch: 7----Gradient norm: 3.6962267729166154----- 0.0230
Epoch: 8----Gradient norm: 3.682736237341477----- 0.0230
Epoch: 9----Gradient norm: 3.669521063066088----- 0.0230
Epoch: 10----Gradient norm: 3.6565775346104----- 0.0230
Epoch: 11----Gradient norm: 3.643902039510399----- 0.0230
Epoch: 12----Gradient norm: 3.631491065559742----- 0.0229
Epoch: 13----Gradient norm: 3.6193411981452943----- 0.0229
Epoch: 14----Gradient norm: 3.607449117672817----- 0.0229
Epoch: 15----Gradient norm: 3.595811597079182----- 0.0229
Epoch: 16----Gradient norm: 3.584425499427663----- 0.0229
Epoch: 17----Gradient norm: 3.5732877755830095----- 0.0228
Epoch: 18----Gradient norm: 3.5623954619631473----- 0.0228
Epoch: 19----Gradient norm: 3.551745678364493----- 0.0228
Epoch: 20----Gradient norm: 3.5413356258579936----- 0.0228
Epoch: 21----Gradient norm: 3.531162584753135----- 0.0228
Epoch: 22----Gradient norm: 3.521223912627274----- 0.0227
Epoch: 23----Gradient norm: 3.5115170424177626----- 0.0227
Epoch: 24----Gradient norm: 3.5020394805744424----- 0.0227
Epoch: 25----Gradient norm: 3.4927888052701794----- 0.0227
Epoch: 26----Gradient norm: 3.483762664667225----- 0.0227
Epoch: 27----Gradient norm: 3.474958775237253----- 0.0227
Epoch: 28----Gradient norm: 3.466374920133038----- 0.0226
Epoch: 29----Gradient norm: 3.458008947609803----- 0.0226
Epoch: 30----Gradient norm: 3.4498587694943508----- 0.0226
Epoch: 31----Gradient norm: 3.4419223597001762----- 0.0226
Epoch: 32----Gradient norm: 3.4341977527868113----- 0.0226
Epoch: 33----Gradient norm: 3.426683042561744----- 0.0226
Epoch: 34----Gradient norm: 3.4193763807232953----- 0.0225
Epoch: 35----Gradient norm: 3.4122759755429253----- 0.0225
Epoch: 36----Gradient norm: 3.405380090585475----- 0.0225
Epoch: 37----Gradient norm: 3.398687043465924----- 0.0225
Epoch: 38----Gradient norm: 3.3921952046412915----- 0.0225
Epoch: 39----Gradient norm: 3.385902996236363----- 0.0225
Epoch: 40----Gradient norm: 3.379808890901965----- 0.0224
Epoch: 41----Gradient norm: 3.3739114107045767----- 0.0224
Epoch: 42----Gradient norm: 3.3682091260460885----- 0.0224
Epoch: 43----Gradient norm: 3.36270065461258----- 0.0224
Epoch: 44----Gradient norm: 3.357384660351024----- 0.0224
Epoch: 45----Gradient norm: 3.352259852472855----- 0.0224
Epoch: 46----Gradient norm: 3.347324984483399----- 0.0223
Epoch: 47----Gradient norm: 3.3425788532361698----- 0.0223
Epoch: 48----Gradient norm: 3.338020298011095----- 0.0223
Epoch: 49----Gradient norm: 3.3336481996157583----- 0.0223
Epoch: 50----Gradient norm: 3.329461479508777----- 0.0223
Epoch: 51----Gradient norm: 3.3254590989444606----- 0.0223
Epoch: 52----Gradient norm: 3.3216400581379357----- 0.0223
Epoch: 53----Gradient norm: 3.318003395449938----- 0.0222
Epoch: 54----Gradient norm: 3.3145481865905153----- 0.0222
Epoch: 55----Gradient norm: 3.311273543840881----- 0.0222
Epoch: 56----Gradient norm: 3.3081786152927286----- 0.0222
Epoch: 57----Gradient norm: 3.305262584104296----- 0.0222
Epoch: 58----Gradient norm: 3.3025246677725137----- 0.0222
Epoch: 59----Gradient norm: 3.2999641174206022----- 0.0221
Epoch: 60----Gradient norm: 3.2975802171004713----- 0.0221
Epoch: 61----Gradient norm: 3.2953722831093395----- 0.0221
Epoch: 62----Gradient norm: 3.2933396633199687----- 0.0221
Epoch: 63----Gradient norm: 3.2914817365239553----- 0.0221
Epoch: 64----Gradient norm: 3.2897979117875322----- 0.0221
Epoch: 65----Gradient norm: 3.2882876278193414----- 0.0221
Epoch: 66----Gradient norm: 3.2869503523496726----- 0.0220
Epoch: 67----Gradient norm: 3.2857855815206594----- 0.0220
Epoch: 68----Gradient norm: 3.284792839286964----- 0.0220
Epoch: 69----Gradient norm: 3.2839716768264697----- 0.0220
Epoch: 70----Gradient norm: 3.283321671960542----- 0.0220
Epoch: 71----Gradient norm: 3.282842428583408----- 0.0220
Epoch: 72----Gradient norm: 3.2825335761002443----- 0.0220
Epoch: 73----Gradient norm: 3.2823947688735484----- 0.0219
Epoch: 74----Gradient norm: 3.282425685677409----- 0.0219
Epoch: 75----Gradient norm: 3.2826260291592813----- 0.0219
Epoch: 76----Gradient norm: 3.2829955253089027----- 0.0219
Epoch: 77----Gradient norm: 3.2835339229339793----- 0.0219
Epoch: 78----Gradient norm: 3.2842409931423036----- 0.0219
Epoch: 79----Gradient norm: 3.285116528829961----- 0.0218
Epoch: 80----Gradient norm: 3.2861603441752982----- 0.0218
Epoch: 81----Gradient norm: 3.2873722741383427----- 0.0218
Epoch: 82----Gradient norm: 3.28875217396536----- 0.0218
Epoch: 83----Gradient norm: 3.2902999186982647----- 0.0218
Epoch: 84----Gradient norm: 3.2920154026885893----- 0.0218
Epoch: 85----Gradient norm: 3.2938985391157436----- 0.0218
Epoch: 86----Gradient norm: 3.2959492595092965----- 0.0217
Epoch: 87----Gradient norm: 3.298167513275023----- 0.0217
Epoch: 88----Gradient norm: 3.3005532672244735----- 0.0217
Epoch: 89----Gradient norm: 3.303106505107824----- 0.0217
Epoch: 90----Gradient norm: 3.305827227149779----- 0.0217
Epoch: 91----Gradient norm: 3.3087154495883078----- 0.0217
Epoch: 92----Gradient norm: 3.311771204216008----- 0.0216
Epoch: 93----Gradient norm: 3.3149945379238774----- 0.0216
Epoch: 94----Gradient norm: 3.318385512247321----- 0.0216
Epoch: 95----Gradient norm: 3.321944202914193----- 0.0216
Epoch: 96----Gradient norm: 3.325670699394694----- 0.0216
Epoch: 97----Gradient norm: 3.329565104452965----- 0.0216
Epoch: 98----Gradient norm: 3.3336275337002053----- 0.0215
Epoch: 99----Gradient norm: 3.337858115149164----- 0.0215

(array([[ 1.81203712e-01,  2.83723290e-01,  3.29830664e-01,
         -1.76019000e-01],
        [ 1.35352754e-01, -3.12719061e-01, -4.58653691e-01,
         -1.12136295e-01],
        [-4.06620496e-01,  6.90821828e-01, -1.21652792e-01,
         -1.87890009e-01],
        [-5.63389699e-02,  1.76253691e-01, -1.90379100e-01,
          1.03178508e-01],
        [-1.48498170e-01,  5.06199630e-01, -6.31502748e-01,
         -1.74732598e-01],
        [-3.54476779e-01, -3.47511121e-01, -3.08684066e-01,
         -2.35779697e-01],
        [ 9.22810149e-02, -3.52080637e-01, -3.35509016e-01,
          1.40845150e-01],
        [ 7.88340796e-02,  1.85566057e-01, -2.78177676e-01,
         -2.44279079e-01],
        [-4.55275756e-01,  2.02112063e-01,  2.43866329e-01,
          4.11975105e-01],
        [-2.02964700e-02,  1.04089756e-01,  2.55792073e-01,
          2.62706459e-01],
        [ 3.56295628e-01,  6.96135719e-02,  3.12528182e-02,
         -2.89126320e-02],
        [-1.74620506e-01,  4.55411862e-01,  3.73475539e-01,
          3.02130581e-02],
        [ 2.37780726e-02, -3.19555274e-01, -1.33444031e-01,
          4.04448205e-01],
        [-1.35675014e-01,  5.61355483e-01, -2.32642231e-01,
          3.96759792e-01],
        [ 1.32372675e-01, -1.71454490e-01, -3.05813663e-01,
          2.42837881e-01],
        [ 3.07298894e-01, -6.75438769e-02, -3.60929580e-02,
          2.98271322e-01],
        [-2.09070491e-01, -1.02225388e-01,  1.75429245e-01,
         -5.05910006e-01],
        [ 1.28319703e-01,  2.12159119e-01, -4.60149355e-02,
         -1.56717379e-01],
        [ 2.25268645e-02, -4.48614114e-01,  1.31401246e-04,
         -3.38788564e-01],
        [ 3.75830585e-01, -4.80045445e-02, -2.53632200e-01,
         -2.48497939e-01]]),
 array([[-0.02286064,  0.01401068, -0.00382394, ..., -0.01395637,
         -0.02047974,  0.0284757 ],
        [-0.01501035, -0.00540898,  0.05518141, ..., -0.05043993,
          0.02135264, -0.04785386],
        [ 0.00558144,  0.02948142, -0.02179302, ...,  0.01054024,
         -0.00183507, -0.06800109],
        [-0.00919402, -0.04262764,  0.00654318, ...,  0.02318953,
          0.06328887, -0.0310658 ]]))